env:
  browser: true
  commonjs: true
  es6: true
  node: true
extends: google
installedESLint: true
parserOptions:
  sourceType: module
rules:
  indent:
    - error
    - 4
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
  semi:
    - error
    - always
  max-len:
    - 1
    - code: 120
